# HTTP Server.
[server]
	address        = ":8080"
	serverRoot     = "public"
	serverAgent    = "gf-demos"
	logPath        = "/tmp/log/srv"
	nameToUriType  = 2
	routeOverWrite = true

# Logger configurations.
[logger]
    path   = "/tmp/log/gf/log"
    level  = "all"
    stdout = true

# Template view configurations.
[viewer]
    path        = "template"
    defaultFile = "index.html"

# Database configurations.
[database]
    link  = "mysql:root:Devops@2021@tcp(127.0.0.1:3306)/daifu"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/gf/sql"
        Level  = "all"
        Stdout = true

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link  = "mysql:root:Devops@2021@tcp(127.0.0.1:3306)/daifu"
        tables = "admin_role"
        removePrefix="admin_"


